site_name: علوم کامپیوتر فردوسی 
nav:
  - صفحه اصلی: index.md
  - دروس پایه:
    - "احتمال م‍قدماتی": base/Elementary-Probability.md
    - "تحلیل داده‌ها با نرم‌افزارهای عمومی": base/Graphical-and-Exploratory-data-analysis.md
    - "ریاضی عمومی ۱": base/Calculus-I.md
    - "ریاضی عمومی ۲": base/Calculus-II.md
    - "کارگاه کامپیوتر ۱": base/Computer-Workshop-I.md
    - "مبانی اقتصاد": base/Basics-of-Economics.md
    - "مبانی کامپیوتر و برنامه‌سازی": base/Fundamentals-of-Computer-Programming.md
    - "معادلات دیفرانسیل": base/Differential-Equations.md
  - دروس الزامی:
    - "اصول سیستم‌های کامپیوتری": mandatory/Principles-of-Computer-Systems.md
    - "آمار محاسباتی": mandatory/Computational-Statistics.md
    - "آمار و احتمال ۱": mandatory/Probability-and-Statistics-I.md
    - "برنامه‌نویسی پایتون": mandatory/Python-Programming.md
    - "برنامه‌نویسی پیشرفته": mandatory/Advanced-Programming.md
    - "بهینه‌سازی غیرخطی": mandatory/Nonlinear-Optimization.md
    - "پایگاه داده": mandatory/Databases.md
    - "تحلیل آماری داده‌ها": mandatory/Statistical-Data-Analysis.md
    - "جبر خطی عددی": mandatory/Numerical-Linear-Algebra.md
    - "داده‌کاوی مقدماتی": mandatory/Elementary-Data-Mining.md
    - "روش‌های آماری": mandatory/Statistical-Methods.md
    - "ساختمان داده و الگوریتم‌ها": mandatory/Data-Structures-and-Algorithms.md
    - "طراحی و تحلیل الگوریتم‌ها": mandatory/Design-and-Analysis-of-Algorithms.md
    - "کارگاه کامپیوتر ۲": mandatory/Computer-Workshop-II.md
    - "مبانی آنالیز ریاضی": mandatory/Foundation-of-Mathematical-Analysis.md
    - "مبانی آنالیزعددی": mandatory/Foundation-of-Numerical-Analysis.md
    - "مبانی ترکیبیات": mandatory/Foundation-of-Combinatorics.md
    - "مبانی علوم ریاضی": mandatory/Foundation-of-Mathematics.md
    - "مبانی ماتریس‌ها و جبرخطی": mandatory/Foundation-of-Matrix-and-Linear-Algebra.md
    - "مبانی منطق و نظریه مجموعه ها": mandatory/Fundamentals-of-Logic.md
    - "مبانی نظریه محاسبه": mandatory/Introduction-to-The-theory-of-Computation.md
    - "یادگیری ماشین  مقدماتی": mandatory/Elementary-Machine-Learning.md
  - دروس اختیاری:
    - "اصول سیستم‌های عامل": elective/Principles-of-Operating-Systems.md
    - "اصول طراحی نرم افزار": elective/Principles-of-SoftwareDesign.md
    - "اصول مصورسازی داده‌ها": elective/Elements-of-data-visualization.md
    - "الگوریتم‌های تصادفی": elective/Randomized-Algorithms.md
    - "آزمایشگاه ریاضی": elective/Mathematics-Lab.md
    - "آشنایی با تحلیل کلان داده‌ها": elective/Introduction-to-Big-Data-Analysis.md
    - "آشنایی با نظریه بازی ها": elective/Introduction-to-Game-Theory.md
    - "آشنایی با یادگیری عمیق": elective/Introduction-to-Deep-Learning.md
    - "آمار و احتمال ۲": elective/Probability-and-Statistics-II.md
    - "آنالیز عددی": elective/Numerical-Analysis.md
    - "برنامه‌نویسی امن": elective/Secure-Programming.md
    - "برنامه‌نویسی موبایل": elective/Mobile-Programming.md
    - "برنامه‌نویسی وب": elective/Web-Programming.md
    - "بهینه‌سازی گسسته": elective/Discrete-Optimization.md
    - "پروژه کارشناسی": elective/Project.md
    - "تجارت الکترونیک": elective/Electronic-Commerce.md
    - "تحقیق در عملیات": elective/Operations-research.md
    - "توسعه کسب و کارهای نوپا": elective/New-Business-Development.md
    - "رایانش چند‌هسته‌ای": elective/Multicore-Computing.md
    - "رگرسیون ۱": elective/Regression-I.md
    - "رمزنگاری": elective/Cryptography.md
    - "ریاضیات فازی": elective/Fuzzy-Mathematics.md
    - "سری های زمانی": elective/Time-Series.md
    - "سیگنال‌ها و سیستم‌ها": elective/Signals-and-Systems.md
    - "شبکه‌های اجتماعی": elective/Social-Networks.md
    - "شبکه‌های کامپیوتری": elective/Computer-Networks.md
    - "شبیه سازی کامپیوتری": elective/Computerized-Simulation.md
    - "فرایند های تصادفی": elective/Stochastic-Processes.md
    - "کارآموزی": elective/Apprenticeship.md
    - "کامپایلر": elective/Compiler.md
    - "گرافیک کامپیوتری": elective/Computer-Graphics.md
    - "مباحثی در الگوریتم‌ها": elective/Topics-in-Algorithms.md
    - "مباحثی در علوم کامپیوتر": elective/Topics-in-Computer-Science.md
    - "مبانی آنالیز فوریه و موجک ها": elective/Introduction-to-Fourier-and-Wavelet-Analysis.md
    - "مبانی بیوانفورماتیک": elective/Fundamentals-of-Bioinformatic.md
    - "مبانی جبر": elective/Foundation-of-Algebra.md
    - "مبانی رایانش ابری": elective/Cloud-Computing-Fundamentals.md
    - "مبانی کارآفرینی": elective/Foundations-of-Entrepreneurship.md
    - "مدلسازی ریاضی": elective/Elementary-Mathematical-Modeling.md
    - "مدیریت پروژه‌های فناوری اطلاعات": elective/Information-Technology-Project-Management.md
    - "مدیریت و کنترل پروژه": elective/Management-and-Project-Control.md
    - "معناشناسی عملیاتی برنامه‌نویسی": elective/Operational-Semantics-of-Programming.md
    - "منطق برای علوم کامپیوتر": elective/Logic-for-Computer-Science.md
    - "نظریه گراف و کاربردها": elective/Graph-Theory-and-Applications.md
    - "نظریه محاسبه": elective/Theory-of-Computation.md
    - "نظریه مقدماتی کد گذاری": elective/Elementary-Coding-Theory.md
    - "هندسه محاسباتی": elective/Computational-Geometry.md
    - "هوش تجاری  مقدماتی": elective/Elementary-Business-intelligence.md
    - "هوش محاسباتی": elective/Computational-Intelligence.md
    - "هوش مصنوعی": elective/Artificial-Intelligence.md
    - "پردازش تصویر مقدماتی": elective/Elementary-Image-Processing.md
    - "مبانی و اصول مدیریت": elective/Basics-and-Principles-of-Management.md


theme:
    name: mkdocs
    locale: fa
