site_name: علوم کامپیوتر فردوسی 
nav:
  - صفحه اصلی: index.md
  - دروس پایه:
    - "آمار و احتمال ۱": base/Probability-and-Statistics-I.md
    - "ریاضی عمومی ۱": base/Calculus-I.md
    - "ریاضی عمومی ۲": base/Calculus-II.md
    - "کارگاه کامپیوتر ۱": base/Computer-Workshop-I.md
    - "مبانی علوم ریاضی": base/Foundation-of-Mathematics.md
    - "مبانی کامپیوتر و برنامه‌سازی": base/Fundamentals-of-Computer-Programming.md
    - "معادلات دیفرانسیل": base/Differential-Equations.md
  - دروس الزامی:
    - "اصول سیستم‌های کامپیوتری": mandatory/Principles-of-Computer-Systems.md
    - "برنامه‌نویسی پایتون": mandatory/Python-Programming.md
    - "برنامه‌نویسی پیشرفته": mandatory/Advanced-Programming.md
    - "بهینه‌سازی غیرخطی": mandatory/Nonlinear-Optimization.md
    - "پایگاه داده‌ها": mandatory/Databases.md
    - "تحقیق در عملیات": mandatory/Operations-research.md
    - "تحلیل آماری داده‌ها": mandatory/Statistical-Data-Analysis.md
    - "داده‌کاوی مقدماتی": mandatory/Elementary-Data-Mining.md
    - "ساختمان داده‌ها و الگوریتم‌ها": mandatory/Data-Structures-and-Algorithms.md
    - "سری‌های زمانی کاربردی": mandatory/Time-Series.md
    - "طراحی و تحلیل الگوریتم‌ها": mandatory/Design-and-Analysis-of-Algorithms.md
    - "طراحی و توسعه کسب و کارهای نوپا": mandatory/Design-and-development-of-start-up-businesses.md
    - "کارآموزی": mandatory/Apprenticeship.md
    - "کارگاه کامپیوتر ۲": mandatory/Computer-Workshop-II.md
    - "مبانی اقتصاد دیجیتال": mandatory/Basics-of-Digital-Economics.md
    - "مبانی آنالیز ریاضی": mandatory/Foundation-of-Mathematical-Analysis.md
    - "مبانی آنالیز عددی": mandatory/Foundation-of-Numerical-Analysis.md
    - "مبانی ترکیبیات": mandatory/Foundation-of-Combinatorics.md
    - "مبانی کارآفرینی": mandatory/Foundations-of-Entrepreneurship.md
    - "مبانی محاسبات علمی": mandatory/Elementary-Scientific-Computing.md
    - "مبانی منطق و نظریه مجموعه‌ها": mandatory/Fundamentals-of-Logic.md
    - "مبانی نظریه محاسبه": mandatory/Introduction-to-the-theory-of-Computation.md
    - "مدلسازی ریاضی": mandatory/Mathematical-Modeling.md
    - "نرم‌افزارهای آماری و تحلیل داده‌ها": mandatory/Statistical-Software-and-data-analysis.md
    - "یادگیری ماشین مقدماتی": mandatory/Elementary-Machine-Learning.md
  - دروس اختیاری:
    - "اصول سیستم‌های عامل": elective/Principles-of-Operating-Systems.md
    - "اصول طراحی نرم افزار": elective/Principles-of-SoftwareDesign.md
    - "الگوریتم‌های تصادفی": elective/Randomized-Algorithms.md
    - "آزمایشگاه ریاضی": elective/Mathematics-Lab.md
    - "آشنایی با کلان داده‌ها": elective/Introduction-to-Big-Data.md
    - "آشنایی با نظریه بازی‌ها": elective/Introduction-to-Game-Theory.md
    - "آشنایی با یادگیری عمیق": elective/Introduction-to-Deep-Learning.md
    - "آمار محاسباتی": elective/Computational-Statistics.md
    - "آمار و احتمال ۲": elective/Probability-and-Statistics-II.md
    - "آنالیز عددی": elective/Numerical-Analysis.md
    - "برنامه‌نویسی امن": elective/Secure-Programming.md
    - "برنامه‌نویسی موبایل": elective/Mobile-Programming.md
    - "برنامه‌نویسی وب": elective/Web-Programming.md
    - "بهینه‌سازی گسسته": elective/Discrete-Optimization.md
    - "پردازش تصویر مقدماتی": elective/Elementary-Image-Processing.md
    - "پروژه کارشناسی": elective/Project.md
    - "تجارت الکترونیک": elective/Electronic-Commerce.md
    - "تحلیل شبکه‌های اجتماعی": elective/Social-Networks-Analysis.md
    - "جبر خطی": elective/Linear-Algebra.md
    - "رایانش چند‌هسته‌ای": elective/Multicore-Computing.md
    - "رگرسیون ۱": elective/Regression-I.md
    - "رمزنگاری": elective/Cryptography.md
    - "روش‌های آماری": elective/Statistical-Methods.md
    - "ریاضیات فازی": elective/Fuzzy-Mathematics.md
    - "سیگنال‌ها و سیستم‌ها": elective/Signals-and-Systems.md
    - "شبکه‌های کامپیوتری": elective/Computer-Networks.md
    - "شبیه سازی کامپیوتری": elective/Computerized-Simulation.md
    - "فرایند های تصادفی": elective/Stochastic-Processes.md
    - "کامپایلر": elective/Compiler.md
    - "گرافیک کامپیوتری": elective/Computer-Graphics.md
    - "مباحثی در علوم کامپیوتر ۱": elective/Topics-in-Computer-Science-I.md
    - "مباحثی در علوم کامپیوتر ۲": elective/Topics-in-Computer-Science-II.md
    - "مبانی آنالیز فوریه و موجک ها": elective/Introduction-to-Fourier-and-Wavelet-Analysis.md
    - "مبانی بیوانفورماتیک": elective/Fundamentals-of-Bioinformatic.md
    - "مبانی جبر": elective/Foundation-of-Algebra.md
    - "مبانی رایانش ابری": elective/Cloud-Computing-Fundamentals.md
    - "مبانی و اصول مدیریت": elective/Basics-and-Principles-of-Management.md
    - "مدیریت پروژه‌های فناوری اطلاعات": elective/Information-Technology-Project-Management.md
    - "معناشناسی عملیاتی برنامه‌نویسی": elective/Operational-Semantics-of-Programming.md
    - "منطق برای علوم کامپیوتر": elective/Logic-for-Computer-Science.md
    - "نظریه گراف و کاربردها": elective/Graph-Theory-and-Applications.md
    - "نظریه محاسبه": elective/Theory-of-Computation.md
    - "نظریه مقدماتی کدگذاری": elective/Elementary-Coding-Theory.md
    - "هندسه محاسباتی": elective/Computational-Geometry.md
    - "هوش تجاری مقدماتی": elective/Elementary-Business-intelligence.md
    - "هوش محاسباتی": elective/Computational-Intelligence.md
    - "هوش مصنوعی": elective/Artificial-Intelligence.md


theme:
    name: mkdocs
    locale: fa
